name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: BakemonoTR/Argus@v1.4
        with:
          groq_api_key: ${{ secrets.GROQ_API_KEY }}
          language : 'tr'